import typography from '@tailwindcss/typography';

/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        workspace: 'rgb(var(--ui-workspace) / <alpha-value>)',
        background: 'rgb(var(--ui-workspace) / <alpha-value>)',
        panel: 'rgb(var(--ui-panel) / <alpha-value>)',
        'panel-muted': 'rgb(var(--ui-panel-muted) / <alpha-value>)',
        canvas: 'rgb(var(--ui-canvas) / <alpha-value>)',
        surface: 'rgb(var(--ui-surface) / <alpha-value>)',
        'timeline-card': 'rgb(var(--ui-timeline-card) / <alpha-value>)',
        ink: 'rgb(var(--ui-foreground) / <alpha-value>)',
        muted: 'rgb(var(--ui-text-600) / <alpha-value>)',
        subtle: 'rgb(var(--ui-text-400) / <alpha-value>)',
        border: 'rgb(var(--ui-border) / <alpha-value>)',
        'border-strong': 'rgb(var(--ui-border-strong) / <alpha-value>)',
        accent: 'rgb(var(--ui-accent) / <alpha-value>)',
        'accent-soft': 'rgb(var(--ui-selected) / <alpha-value>)',
        'accent-hover': 'rgb(var(--ui-accent-hover) / <alpha-value>)',
        hover: 'rgb(var(--ui-hover) / <alpha-value>)',
        selected: 'rgb(var(--ui-selected) / <alpha-value>)',
        'selected-foreground': 'rgb(var(--ui-selected-foreground) / <alpha-value>)',
        success: 'rgb(var(--ui-success) / <alpha-value>)',
        'success-soft': 'rgb(var(--ui-success-soft) / <alpha-value>)',
        warning: 'rgb(var(--ui-warning) / <alpha-value>)',
        'warning-soft': 'rgb(var(--ui-warning-soft) / <alpha-value>)',
        danger: 'rgb(var(--ui-danger) / <alpha-value>)',
        'danger-soft': 'rgb(var(--ui-danger-soft) / <alpha-value>)',
        text: {
          900: 'rgb(var(--ui-foreground) / <alpha-value>)',
          800: 'rgb(var(--ui-text-800) / <alpha-value>)',
          700: 'rgb(var(--ui-text-700) / <alpha-value>)',
          600: 'rgb(var(--ui-text-600) / <alpha-value>)',
          500: 'rgb(var(--ui-text-500) / <alpha-value>)',
          400: 'rgb(var(--ui-text-400) / <alpha-value>)',
        },
      },
      typography: { DEFAULT: { css: {
        '--tw-prose-body': 'rgb(var(--ui-text-700))',
        '--tw-prose-headings': 'rgb(var(--ui-foreground))',
        '--tw-prose-lead': 'rgb(var(--ui-text-600))',
        '--tw-prose-links': 'rgb(var(--ui-selected-foreground))',
        '--tw-prose-bold': 'rgb(var(--ui-foreground))',
        '--tw-prose-counters': 'rgb(var(--ui-text-600))',
        '--tw-prose-bullets': 'rgb(var(--ui-text-400))',
        '--tw-prose-hr': 'rgb(var(--ui-border))',
        '--tw-prose-quotes': 'rgb(var(--ui-text-800))',
        '--tw-prose-quote-borders': 'rgb(var(--ui-border-strong))',
        '--tw-prose-captions': 'rgb(var(--ui-text-600))',
        '--tw-prose-code': 'rgb(var(--ui-text-800))',
        '--tw-prose-pre-code': 'rgb(var(--ui-text-800))',
        '--tw-prose-pre-bg': 'rgb(var(--ui-panel-muted))',
        '--tw-prose-th-borders': 'rgb(var(--ui-border-strong))',
        '--tw-prose-td-borders': 'rgb(var(--ui-border))',
      } } },
      fontFamily: {
        sans: ['Aptos', 'Inter', '-apple-system', 'BlinkMacSystemFont', '"SF Pro Text"', '"PingFang SC"', '"Microsoft YaHei"', 'sans-serif'],
        mono: ['"SFMono-Regular"', 'Consolas', '"Liberation Mono"', 'monospace'],
      },
      boxShadow: {
        canvas: 'var(--shadow-canvas)',
        overlay: 'var(--shadow-overlay)',
        card: 'var(--shadow-card)',
        switch: 'var(--shadow-switch)',
      },
    },
  },
  plugins: [typography],
}
