// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/dasi0227/PPT-Agent/backend/internal/config"
	"github.com/dasi0227/PPT-Agent/backend/internal/httpapi"
	"github.com/dasi0227/PPT-Agent/backend/internal/logger"
	"github.com/dasi0227/PPT-Agent/backend/internal/persistence"
	"github.com/dasi0227/PPT-Agent/backend/internal/run"
	"github.com/dasi0227/PPT-Agent/backend/internal/service"
	"github.com/dasi0227/PPT-Agent/backend/internal/store"
	"github.com/dasi0227/PPT-Agent/backend/internal/store/sqlite"
	"github.com/google/wire"
)

// Injectors from wire.go:

func initApp(cfg *config.Config) (*App, func(), error) {
	zapLogger, cleanup, err := logger.New(cfg)
	if err != nil {
		return nil, nil, err
	}
	db, cleanup2, err := sqlite.Open(cfg, zapLogger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	store, err := persistence.NewStore(db, zapLogger)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	healthService := service.NewHealthService(store)
	healthHandler := httpapi.NewHealthHandler(healthService)
	lockManager := provideLockManager()
	engine, err := provideEngine(store, lockManager, zapLogger)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	registry, err := provideLLMRegistry(cfg)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	workRoot := provideWorkRoot(cfg)
	nodeSlideRenderer, cleanup3, err := provideRenderWorker()
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	journalTranscriptStore := provideTranscriptStore(store)
	calibrationStore := provideCalibrationStore()
	provider, err := provideRenameProvider(registry)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	threadEventHub := provideThreadEventHub(store)
	namingService, cleanup4 := provideNamingService(store, provider, registry, threadEventHub, zapLogger)
	gitCommitService, err := provideGitCommitService(store, registry, lockManager)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	runService := provideRunService(store, engine, registry, workRoot, nodeSlideRenderer, journalTranscriptStore, calibrationStore, namingService, gitCommitService)
	runHandler := httpapi.NewRunHandler(runService)
	themeService := provideThemeService(store, workRoot)
	manager, cleanup5, err := provideExportManager(nodeSlideRenderer, workRoot, zapLogger)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	projectService := provideProjectService(store, workRoot, lockManager, themeService, manager)
	pptMutationService := providePPTMutationService(store, lockManager)
	projectHandler := httpapi.NewProjectHandler(projectService, pptMutationService)
	threadService := provideThreadService(store, journalTranscriptStore)
	threadHandler := provideThreadHandler(threadService, namingService)
	slideService := provideSlideService(store)
	slideHandler := httpapi.NewSlideHandler(slideService)
	componentService := provideComponentService(store, workRoot)
	skillService := provideSkillService(store, workRoot)
	repositoryHandler := httpapi.NewRepositoryHandler(themeService, componentService, skillService)
	llmHandler := httpapi.NewLLMHandler(registry)
	polishService := service.NewPolishService(store, registry)
	polishHandler := httpapi.NewPolishHandler(polishService)
	handoffService := service.NewHandoffService(store, registry, lockManager)
	briefingHandler := httpapi.NewBriefingHandler(handoffService)
	gitCommitHandler := httpapi.NewGitCommitHandler(gitCommitService)
	resourceService, err := provideResourceService(store, workRoot)
	if err != nil {
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	resourceHandler := httpapi.NewResourceHandler(resourceService)
	contextWindowService := service.NewContextWindowService(store, registry, lockManager, journalTranscriptStore, calibrationStore)
	contextWindowHandler := httpapi.NewContextWindowHandler(contextWindowService)
	attachmentService := provideAttachmentService(store, lockManager)
	attachmentHandler := httpapi.NewAttachmentHandler(attachmentService)
	exportService := service.NewExportService(store, lockManager, themeService, manager)
	exportHandler := httpapi.NewExportHandler(exportService)
	router, err := provideRouter(cfg, zapLogger, healthHandler, runHandler, projectHandler, threadHandler, slideHandler, repositoryHandler, llmHandler, polishHandler, briefingHandler, gitCommitHandler, resourceHandler, contextWindowHandler, attachmentHandler, exportHandler, store)
	if err != nil {
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	ginEngine := engineFromRouter(router)
	server := provideHTTPServer(cfg, ginEngine)
	app := provideApp(server, engine, runService, zapLogger)
	return app, func() {
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}

// wire.go:

// providerSet 声明全部 provider；wire 在编译期据此生成装配代码。
var providerSet = wire.NewSet(logger.New, sqlite.Open, persistence.NewStore, wire.Bind(new(store.Store), new(*sqlite.Store)), wire.Bind(new(run.Store), new(*sqlite.Store)), provideLLMRegistry,
	provideRenameProvider,
	provideThreadEventHub,
	provideNamingService,
	provideLockManager,
	provideTranscriptStore,
	provideCalibrationStore,
	provideWorkRoot,
	provideEngine,
	provideRenderWorker,
	provideExportManager, service.NewHealthService, provideProjectService,
	provideThreadService,
	provideAttachmentService, service.NewExportService, provideRunService, service.NewContextWindowService, service.NewPolishService, service.NewHandoffService, provideGitCommitService,
	provideSlideService,
	providePPTMutationService,
	provideThemeService,
	provideComponentService,
	provideSkillService,
	provideResourceService, httpapi.NewHealthHandler, httpapi.NewRunHandler, httpapi.NewAttachmentHandler, httpapi.NewExportHandler, httpapi.NewPolishHandler, httpapi.NewBriefingHandler, httpapi.NewGitCommitHandler, httpapi.NewLLMHandler, httpapi.NewProjectHandler, provideThreadHandler, httpapi.NewContextWindowHandler, httpapi.NewSlideHandler, httpapi.NewRepositoryHandler, httpapi.NewResourceHandler, provideRouter,
	engineFromRouter,
	provideHTTPServer,
	provideApp,
)
