// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/dasi0227/PPT-Agent/backend/internal/config"
	"github.com/dasi0227/PPT-Agent/backend/internal/httpapi"
	"github.com/dasi0227/PPT-Agent/backend/internal/logger"
	"github.com/dasi0227/PPT-Agent/backend/internal/run"
	"github.com/dasi0227/PPT-Agent/backend/internal/service"
	"github.com/dasi0227/PPT-Agent/backend/internal/store"
	"github.com/dasi0227/PPT-Agent/backend/internal/store/sqlite"
	"github.com/google/wire"
)

// Injectors from wire.go:

func initApp() (*App, func(), error) {
	configConfig, err := config.Load()
	if err != nil {
		return nil, nil, err
	}
	zapLogger, cleanup, err := logger.New(configConfig)
	if err != nil {
		return nil, nil, err
	}
	db, cleanup2, err := sqlite.Open(configConfig, zapLogger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	store, err := sqlite.NewStore(db, zapLogger)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	healthService := service.NewHealthService(store)
	healthHandler := httpapi.NewHealthHandler(healthService)
	lockManager := provideLockManager()
	engine := provideEngine(store, lockManager, zapLogger)
	client := provideLLMClient(configConfig)
	workRoot := provideWorkRoot(configConfig)
	runService := service.NewRunService(store, engine, client, workRoot)
	runHandler := httpapi.NewRunHandler(runService)
	slideService := service.NewSlideService(store)
	slideHandler := httpapi.NewSlideHandler(slideService)
	assetService := provideAssetService(store, workRoot)
	assetHandler := httpapi.NewAssetHandler(assetService)
	router := httpapi.NewRouter(configConfig, zapLogger, healthHandler, runHandler, slideHandler, assetHandler)
	ginEngine := engineFromRouter(router)
	server := provideHTTPServer(configConfig, ginEngine)
	mainSeedDone, err := provideSeed(configConfig, store, zapLogger)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	app := provideApp(server, zapLogger, mainSeedDone)
	return app, func() {
		cleanup2()
		cleanup()
	}, nil
}

// wire.go:

// providerSet 声明全部 provider；wire 在编译期据此生成装配代码。
var providerSet = wire.NewSet(config.Load, logger.New, sqlite.Open, sqlite.NewStore, wire.Bind(new(store.Store), new(*sqlite.Store)), wire.Bind(new(run.Store), new(*sqlite.Store)), provideLLMClient,
	provideLockManager,
	provideWorkRoot,
	provideAssetService,
	provideEngine, service.NewHealthService, service.NewRunService, service.NewSlideService, httpapi.NewHealthHandler, httpapi.NewRunHandler, httpapi.NewSlideHandler, httpapi.NewRouter, engineFromRouter,
	httpapi.NewAssetHandler,
	provideHTTPServer,
	provideSeed,
	provideApp,
)
