ALTER TABLE projects ADD COLUMN deck_path TEXT NOT NULL DEFAULT 'deck.json';
ALTER TABLE projects ADD COLUMN deck_revision INTEGER NOT NULL DEFAULT 0;
ALTER TABLE projects ADD COLUMN design_revision INTEGER NOT NULL DEFAULT 0;

ALTER TABLE slides ADD COLUMN blueprint_revision INTEGER NOT NULL DEFAULT 0;
ALTER TABLE slides ADD COLUMN presentation_revision INTEGER NOT NULL DEFAULT 0;
ALTER TABLE slides ADD COLUMN source_deck_revision INTEGER NOT NULL DEFAULT 0;
ALTER TABLE slides ADD COLUMN source_blueprint_revision INTEGER NOT NULL DEFAULT 0;
ALTER TABLE slides ADD COLUMN source_design_revision INTEGER NOT NULL DEFAULT 0;
