-- Superseded development schema.
--
-- The repository now has one canonical v6 bootstrap schema at
-- backend/migrations/0001_init.sql. This project intentionally does not
-- migrate prior development databases: remove the local database and project
-- work directory before running the breaking-refactor build.
